### ISSUE TITLE
Use of unresolved identifier '_sanityCheck' and '_precondition'

### ISSUE THREAD

**Issue by Zhimin90** [EvaCoop/react-native-eos#5]
I tried to build with the latest Xcode but got these errors, looks like they are from exernal libraries some where?
![Swift](https://user-images.githubusercontent.com/47169451/57053422-8884ca00-6c53-11e9-8129-60ffe7a60ca8.PNG)

**Comment by nuwanwre** [comment]
For anyone who encounter this issue, [this](https://github.com/ProChain/SwiftyEOS/issues/52) should help.

**Comment by raphaelgodro** [comment]
Problem solved
